# Generated by Django 3.2.6 on 2021-08-11 11:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=15)),
                ('opcao', models.CharField(choices=[('A', 'Ativo'), ('B', 'Bloqueado'), ('C', 'Cancelado')], default='A', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=50)),
                ('datainicio', models.DateTimeField(default=datetime.datetime(2021, 8, 11, 11, 12, 41, 340876, tzinfo=utc))),
                ('mostrar', models.BooleanField(default=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.professor')),
            ],
        ),
    ]
