# Generated by Django 3.2.6 on 2021-08-11 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_curso_datainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='datainicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 12, 49, 37, 666752, tzinfo=utc)),
        ),
    ]
